apiVersion: v1
kind: Service
metadata:
  name: quintus
  labels:
    app: quintus
spec:
   ports:
    - name: mongo
      port: 27017
      nodePort: 27017
    - name: postgres
      port: 5432
      nodePort: 5432
   type: NodePort
   selector:
    app: quintus
