flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
  individual_flags:
    - name: helpers
      paths:
      - quintus/src/helpers
      carryforward: true
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 100%
    - name: structures
      paths:
      - quintus/src/structures
      carryforward: true
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 100%
    - name: io
      paths:
      - quintus/src/io
      carryforward: true
      statuses:
      - type: project
        target: 20%
      - type: patch
        target: 100%
    - name: evaluations
      paths:
      - quintus/src/evaluations
      carryforward: true
      statuses:
      - type: project
        target: 20%
      - type: patch
        target: 100%
    - name: runner
      paths:
      - quintus/src/runner
      carryforward: true
      statuses:
      - type: project
        target: 20%
      - type: patch
        target: 100%
    - name: composites
      paths:
      - composites/src
      carryforward: true
      statuses:
      - type: project
        target: 20%
      - type: patch
        target: 100%
