[tool.pdm]

[project]
name = "quintus"
version = "0.1.0"
description = "Help you find the optimal configuration from a set of materials."
authors = [
    {name = "Willi Zschiebsch", email = "willi.zschiebsch@gmail.com"},
]
dependencies = [
    "openpyxl>=3.1.1",
    "polars>=0.16.11",
    "optuna>=3.1.0",
    "numpy>=1.24.2",
    "pymongo>=4.3.3",
    "pydantic>=1.10.6",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project.optional-dependencies]
test = [
    "coverage>=7.1.0",
    "pytest>=7.2.1",
]
visual=[
    "flask>=2.2.3",
    "optuna-dashboard>=0.8.1",
]
all = ["quintus[visual,test]"]
