apiVersion: v1
kind: Pod
metadata:
  labels:
    app: quintus
  name: quintus
spec:
  containers:
  - name: mongo
    image: docker.io/library/mongo:latest
    ports:
      - containerPort: 27017
    volumeMounts:
    - mountPath: /data/db
      name: mongodb

  - name: postgres
    image: docker.io/library/postgres:latest
    imagePullPolocy: "IfNotPresent"
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: postgres-secrets
            key: db-username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secrets
            key: db-password
      - name: POSTGRES_DB
        value: quintus
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: postgredb


  volumes:
    - name: postgredb
      persistentVolumeClaim:
        claimName: postgres-pv-claim

    - name: mongodb
      persistentVolumeClaim:
        claimName: mongo-pv-claim
